### ISSUE TITLE
プロジェクト側で追加された依存関係への対応

### ISSUE THREAD

**Issue by Javakky-pxv** [pixiv/scalafix-pixiv-rule#22]
対象プロジェクトのクラスパスから `.jar` の位置を特定してクラスローダーを作り直せばできそう？

結構重そうなのと、そこまでやる必要があるのかは検討したほうがよい。
(例えば `Seq` を継承した高速リスト〜みたいなライブラリを使ってたりすることを想定するならあっても便利かもしれない)

**Comment by Javakky** [comment]
Mockitoのやつ ( #40 ) のように、特定のライブラリに対するルールの場合のみ追加し、全ての依存関係を動的に把握するようなことは一旦しない

**Comment by Javakky-pxv** [comment]
Mockitoのやつ ( https://github.com/pixiv/scalafix-pixiv-rule/pull/40 ) のように、特定のライブラリに対するルールの場合のみ追加し、全ての依存関係を動的に把握するようなことは一旦しない
